@extends ('layouts.template-landing-page.web.master')

@include ('app.hosting-plans.pricing.domain.section1')
@include ('app.hosting-plans.pricing.domain.section2')
@include ('app.hosting-plans.pricing.domain.section3')
@include ('app.hosting-plans.pricing.domain.section4')
@include ('app.hosting-plans.pricing.domain.section5')
@include ('app.hosting-plans.pricing.domain.section6')
@include ('app.hosting-plans.pricing.domain.section7')
@include ('app.hosting-plans.pricing.domain.section8')